CREATE TABLE `player_character_performance_snapshots` (
  `id` VARCHAR(255) NOT NULL,
  `canonical_uid` VARCHAR(128) NOT NULL,
  `display_season_id` INTEGER NOT NULL,
  `api_season_id` INTEGER NOT NULL,
  `character_num` INTEGER NOT NULL,
  `benchmark_scope` VARCHAR(24) NOT NULL,
  `benchmark_version` VARCHAR(64) NOT NULL,
  `sample_status` VARCHAR(24) NOT NULL,
  `eligible_matches` INTEGER NOT NULL,
  `average_placement` DOUBLE NULL,
  `win_rate` DOUBLE NULL,
  `top3_rate` DOUBLE NULL,
  `average_kills` DOUBLE NULL,
  `average_deaths` DOUBLE NULL,
  `team_kill_participation` DOUBLE NULL,
  `damage_per_minute` DOUBLE NULL,
  `damage_share` DOUBLE NULL,
  `vision_per_minute` DOUBLE NULL,
  `average_survival_time` DOUBLE NULL,
  `consistency_score` DOUBLE NULL,
  `shadow_score` DOUBLE NULL,
  `primary_role` VARCHAR(32) NULL,
  `tier_band` VARCHAR(32) NULL,
  `sample_window_start` DATETIME(3) NOT NULL,
  `sample_window_end` DATETIME(3) NOT NULL,
  `source_fingerprint` VARCHAR(128) NOT NULL,
  `computed_at` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `pcps_uid_season_char_scope_ver_key` (`canonical_uid`, `display_season_id`, `character_num`, `benchmark_scope`, `benchmark_version`),
  INDEX `pcps_season_char_scope_idx` (`display_season_id`, `character_num`, `benchmark_scope`),
  INDEX `pcps_season_scope_status_idx` (`display_season_id`, `benchmark_scope`, `sample_status`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
