import type { AnalysisMetricDefinition } from '@/analysis/metricTypes'

export const ANALYSIS_METRIC_CATALOG: readonly AnalysisMetricDefinition[] = [
  // ── result / summary ──
  {
    id: 'winRate',
    label: '승률',
    category: 'result',
    availability: 'derived',
    description: '1위 비율',
    sourceHint: 'BattleUserResult.victory',
    valueType: 'percent',
    higherIsBetter: true,
    isPrimary: true,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'avgPlacement',
    label: '평균 순위',
    category: 'result',
    availability: 'available',
    description: '최근 랭크 평균 등수',
    sourceHint: 'BattleUserResult.gameRank',
    valueType: 'number',
    higherIsBetter: false,
    isPrimary: true,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'top3Rate',
    label: 'TOP3 비율',
    category: 'result',
    availability: 'derived',
    description: '3위 이내 비율',
    sourceHint: 'BattleUserResult.gameRank',
    valueType: 'percent',
    higherIsBetter: true,
    isPrimary: true,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'top2Rate',
    label: 'TOP2 비율',
    category: 'result',
    availability: 'derived',
    description: '2위 이내 비율',
    sourceHint: 'BattleUserResult.gameRank',
    valueType: 'percent',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'sampleSize',
    label: '표본 수',
    category: 'result',
    availability: 'available',
    description: '분석에 사용된 경기 수',
    sourceHint: 'userGames 목록 길이',
    valueType: 'number',
    higherIsBetter: false,
    isPrimary: true,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },

  // ── survival ──
  {
    id: 'avgDeaths',
    label: '평균 데스',
    category: 'survival',
    availability: 'available',
    description: '경기당 사망 횟수',
    sourceHint: 'BattleUserResult.playerDeaths',
    valueType: 'number',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'avgSurvivalTime',
    label: '평균 생존시간',
    category: 'survival',
    availability: 'available',
    description: '경기 종료까지 플레이 시간',
    sourceHint: 'BattleUserResult.playTime',
    valueType: 'time',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'bottomRate',
    label: '하위권 비율',
    category: 'survival',
    availability: 'derived',
    description: '7위 이하 비율',
    sourceHint: 'BattleUserResult.gameRank',
    valueType: 'percent',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },

  // ── combat ──
  {
    id: 'tkInvolvementRate',
    label: 'TK 관여율',
    category: 'combat',
    availability: 'derived',
    description: '팀 킬 대비 (킬+어시) 비율',
    sourceHint: 'BattleUserResult.teamKill, playerKill, playerAssistant',
    valueType: 'percent',
    higherIsBetter: true,
    isPrimary: true,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'avgPersonDamage',
    label: '평균 사람 딜량',
    category: 'combat',
    availability: 'available',
    description: '플레이어 대상 피해량',
    sourceHint: 'BattleUserResult.damageToPlayer',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'avgKills',
    label: '평균 킬',
    category: 'combat',
    availability: 'available',
    description: '경기당 플레이어 처치',
    sourceHint: 'BattleUserResult.playerKill',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'avgDamageTaken',
    label: '평균 받은 피해량',
    category: 'combat',
    availability: 'available',
    description: '플레이어로부터 받은 피해',
    sourceHint: 'BattleUserResult.damageFromPlayer',
    valueType: 'number',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'ccTimeToPlayer',
    label: 'CC 시간',
    category: 'combat',
    availability: 'available',
    description: '플레이어 대상 군중 제어 시간',
    sourceHint: 'BattleUserResult.ccTimeToPlayer',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'avgAssists',
    label: '평균 어시',
    category: 'combat',
    availability: 'available',
    description: '경기당 어시스트',
    sourceHint: 'BattleUserResult.playerAssistant',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'kda',
    label: 'KDA',
    category: 'combat',
    availability: 'derived',
    description: '(킬+어시)/데스',
    sourceHint: 'playerKill, playerAssistant, playerDeaths',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },

  // ── macro ──
  {
    id: 'avgAnimalKills',
    label: '평균 동물 처치',
    category: 'macro',
    availability: 'available',
    description: '야생 동물 처치 수',
    sourceHint: 'BattleUserResult.monsterKill',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'avgMonsterDamage',
    label: '평균 동물 딜량',
    category: 'macro',
    availability: 'available',
    description: '몬스터 대상 피해량',
    sourceHint: 'BattleUserResult.damageToMonster',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'avgCreditGained',
    label: '평균 획득 크레딧',
    category: 'macro',
    availability: 'available',
    description: '경기당 획득 VF 크레딧',
    sourceHint: 'BattleUserResult.totalGainVFCredit',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'avgCreditUsed',
    label: '평균 사용 크레딧',
    category: 'macro',
    availability: 'available',
    description: '경기당 사용 VF 크레딧',
    sourceHint: 'BattleUserResult.totalUseVFCredit',
    valueType: 'number',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'creditPerMinute',
    label: '분당 크레딧',
    category: 'macro',
    availability: 'derived',
    description: '획득 크레딧 / 플레이 시간',
    sourceHint: 'totalGainVFCredit, playTime',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'useHyperLoop',
    label: '하이퍼루프 사용',
    category: 'macro',
    availability: 'available',
    description: '경기당 하이퍼루프 사용 횟수',
    sourceHint: 'BattleUserResult.useHyperLoop',
    valueType: 'number',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'useSecurityConsole',
    label: '보안 콘솔 사용',
    category: 'macro',
    availability: 'available',
    description: '경기당 보안 콘솔 사용 횟수',
    sourceHint: 'BattleUserResult.useSecurityConsole',
    valueType: 'number',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },

  // ── support ──
  {
    id: 'viewContribution',
    label: '시야 기여도',
    category: 'support',
    availability: 'available',
    description: '시야 기여 점수 합계',
    sourceHint: 'BattleUserResult.viewContribution',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'surveillanceCamera',
    label: '감시 카메라',
    category: 'support',
    availability: 'available',
    description: '설치·파괴 합산(보조)',
    sourceHint: 'addSurveillanceCamera, removeSurveillanceCamera',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'reconDrone',
    label: '정찰 드론',
    category: 'support',
    availability: 'available',
    description: '정찰 드론 사용 횟수',
    sourceHint: 'BattleUserResult.useReconDrone',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'empDrone',
    label: 'EMP 드론',
    category: 'support',
    availability: 'available',
    description: 'EMP 드론 사용 횟수',
    sourceHint: 'BattleUserResult.useEmpDrone',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'teamRecover',
    label: '팀 회복량',
    category: 'support',
    availability: 'available',
    description: '아군에게 제공한 회복량',
    sourceHint: 'BattleUserResult.teamRecover',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'protectAbsorb',
    label: '보호막 흡수',
    category: 'support',
    availability: 'available',
    description: '보호막으로 흡수한 피해량',
    sourceHint: 'BattleUserResult.protectAbsorb',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },

  // ── consistency ──
  {
    id: 'placementStdDev',
    label: '순위 변동폭',
    category: 'consistency',
    availability: 'derived',
    description: '등수 표준편차 — 낮을수록 안정',
    sourceHint: 'gameRank 집계',
    valueType: 'number',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'halfPlacementGap',
    label: '전반·후반 성적 차',
    category: 'consistency',
    availability: 'derived',
    description: '최근 절반 vs 이전 절반 평균 순위 차',
    sourceHint: 'gameRank 시계열',
    valueType: 'number',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'lateTransitionDelta',
    label: '후반 전환',
    category: 'consistency',
    availability: 'derived',
    description: '최근 vs 이전 순위 변화',
    sourceHint: 'gameRank 시계열',
    valueType: 'number',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
  {
    id: 'kdaCoefficientOfVariation',
    label: 'KDA 변동계수',
    category: 'consistency',
    availability: 'derived',
    description: 'KDA 흐름 안정성',
    sourceHint: 'playerKill, playerAssistant, playerDeaths',
    valueType: 'number',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },

  // ── team (requiresMatchDetail — 구조만) ──
  {
    id: 'teamDamageShare',
    label: '팀 내 딜 기여',
    category: 'team',
    availability: 'requiresMatchDetail',
    description: '팀 총 딜량 중 내 비율',
    sourceHint: '/v1/games/{gameId} 전체 BattleUserResult',
    valueType: 'percent',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: true,
    requiresPopulationDataset: false,
  },
  {
    id: 'teamMonsterDamageShare',
    label: '팀 내 동물 딜 기여',
    category: 'team',
    availability: 'requiresMatchDetail',
    description: '팀 동물 딜량 중 내 비율',
    sourceHint: '/v1/games/{gameId}',
    valueType: 'percent',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: true,
    requiresPopulationDataset: false,
  },
  {
    id: 'teamCreditShare',
    label: '팀 내 크레딧 기여',
    category: 'team',
    availability: 'requiresMatchDetail',
    description: '팀 크레딧 중 내 비율',
    sourceHint: '/v1/games/{gameId}',
    valueType: 'percent',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: true,
    requiresPopulationDataset: false,
  },
  {
    id: 'teamVisionShare',
    label: '팀 내 시야 기여',
    category: 'team',
    availability: 'requiresMatchDetail',
    description: '팀 시야 기여 중 내 비율',
    sourceHint: '/v1/games/{gameId}',
    valueType: 'percent',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: true,
    requiresPopulationDataset: false,
  },
  {
    id: 'lobbyMmrComparison',
    label: '로비 평균 대비 팀운',
    category: 'team',
    availability: 'requiresMatchDetail',
    description: '로비·팀 MMR 비교',
    sourceHint: 'BattleUserResult.mmrAvg, mmrBefore',
    valueType: 'text',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: true,
    requiresPopulationDataset: false,
  },
  {
    id: 'partyPowerComparison',
    label: '파티 전력 비교',
    category: 'team',
    availability: 'requiresMatchDetail',
    description: '팀운 비교',
    sourceHint: '/v1/games/{gameId}',
    valueType: 'text',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: true,
    requiresPopulationDataset: false,
  },

  // ── requiresDataset ──
  {
    id: 'populationPercentile',
    label: '전체 유저 백분위',
    category: 'result',
    availability: 'requiresDataset',
    description: '서비스 데이터 축적 후 제공',
    sourceHint: '자체 집계 DB',
    valueType: 'percent',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: true,
    hidden: true,
  },
  {
    id: 'sssGrade',
    label: 'SSS 등급',
    category: 'result',
    availability: 'requiresDataset',
    description: '데이터 축적 후 등급 제공',
    sourceHint: '자체 집계 DB',
    valueType: 'text',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: true,
    hidden: true,
  },
  {
    id: 'rolePopulationAverage',
    label: '역할별 평균 대비',
    category: 'result',
    availability: 'requiresDataset',
    description: '역할군 평균 대비 점수',
    sourceHint: '자체 집계 DB',
    valueType: 'score',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: true,
    hidden: true,
  },
  {
    id: 'tierPopulationAverage',
    label: '티어 평균 대비',
    category: 'result',
    availability: 'requiresDataset',
    description: '티어별 백분위',
    sourceHint: '자체 집계 DB',
    valueType: 'score',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: true,
    hidden: true,
  },

  // ── experimental / hidden ──
  {
    id: 'roleTendencyPrimary',
    label: '추정 성향',
    category: 'result',
    availability: 'derived',
    description: '최근 플레이 경향(실험)',
    sourceHint: '6축 내부 추정',
    valueType: 'text',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
    experimental: true,
    hidden: true,
  },
  {
    id: 'roleTendencySecondary',
    label: '보조 경향',
    category: 'result',
    availability: 'derived',
    description: '최근 플레이 보조 경향(실험)',
    sourceHint: '6축 내부 추정',
    valueType: 'text',
    higherIsBetter: false,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
    experimental: true,
    hidden: true,
  },
  {
    id: 'roleFitScore',
    label: '역할 적합도',
    category: 'result',
    availability: 'derived',
    description: '가중치 미확정 실험 지표',
    sourceHint: '내부 6축 가중',
    valueType: 'score',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
    experimental: true,
    hidden: true,
  },
  {
    id: 'analysisScore',
    label: '분석 점수',
    category: 'result',
    availability: 'derived',
    description: '최근 경기 기준 플레이 레이더 점수',
    sourceHint: '내부 레이더 계산',
    valueType: 'score',
    higherIsBetter: true,
    isPrimary: false,
    requiresTeamDetail: false,
    requiresPopulationDataset: false,
  },
] as const

export type AnalysisMetricId = (typeof ANALYSIS_METRIC_CATALOG)[number]['id']

const SECTION_LABELS: Record<string, string> = {
  result: '성과',
  survival: '생존',
  combat: '교전',
  macro: '운영',
  support: '지원',
  consistency: '일관성',
  team: '팀운',
}

export function getSectionLabel(category: string): string {
  return SECTION_LABELS[category] ?? category
}

export function getMetricDefinition(id: string): AnalysisMetricDefinition | undefined {
  return ANALYSIS_METRIC_CATALOG.find((m) => m.id === id)
}

export function getCatalogMetricIds(): string[] {
  return ANALYSIS_METRIC_CATALOG.map((m) => m.id)
}

export function getPrimaryMetrics(): AnalysisMetricDefinition[] {
  return ANALYSIS_METRIC_CATALOG.filter((m) => m.isPrimary && !m.hidden)
}

export function getVisibleCatalogMetrics(): AnalysisMetricDefinition[] {
  return ANALYSIS_METRIC_CATALOG.filter((m) => !m.hidden)
}

export function getFutureAvailabilityMetrics(): AnalysisMetricDefinition[] {
  return ANALYSIS_METRIC_CATALOG.filter(
    (m) => m.availability === 'requiresMatchDetail' || m.availability === 'requiresDataset',
  )
}

export function assertCatalogIntegrity(): void {
  const ids = ANALYSIS_METRIC_CATALOG.map((m) => m.id)
  const unique = new Set(ids)
  if (unique.size !== ids.length) {
    throw new Error('Duplicate metric catalog ids')
  }
}
